# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cogo < Formula
  desc "A terminal-native agentic CLI for Go developers."
  homepage "https://github.com/go-steer/cogo"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-steer/cogo/releases/download/v0.3.2/cogo_0.3.2_darwin_amd64.tar.gz"
      sha256 "e53e6e0766f4ac3d290df84a5c08be98bd5b48c427169205ff286de7f015ae19"

      define_method(:install) do
        bin.install "cogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-steer/cogo/releases/download/v0.3.2/cogo_0.3.2_darwin_arm64.tar.gz"
      sha256 "05e15c90a986fab64953de16ce60e7ceaaf3052d43af707e29f9c60a5d59fdfa"

      define_method(:install) do
        bin.install "cogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-steer/cogo/releases/download/v0.3.2/cogo_0.3.2_linux_amd64.tar.gz"
      sha256 "ce247adc15be6c144c5805a27b3d03b846a7625097176389193ec4f41467e6ad"
      define_method(:install) do
        bin.install "cogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-steer/cogo/releases/download/v0.3.2/cogo_0.3.2_linux_arm64.tar.gz"
      sha256 "f2671be10b361105ae605960ace536373ce16d2be3722677d4a35b77ec2b0a1c"
      define_method(:install) do
        bin.install "cogo"
      end
    end
  end

  test do
    assert_match "cogo", shell_output("#{bin}/cogo --version")
  end
end
