# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cogo < Formula
  desc "A terminal-native agentic CLI for Go developers."
  homepage "https://github.com/go-steer/cogo"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-steer/cogo/releases/download/v0.1.1/cogo_0.1.1_darwin_amd64.tar.gz"
      sha256 "36b63ea15465a2f871181c6e165f1767d610381d2adb6b3ccfff019edba5afe3"

      define_method(:install) do
        bin.install "cogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-steer/cogo/releases/download/v0.1.1/cogo_0.1.1_darwin_arm64.tar.gz"
      sha256 "54e3e0c42e28cd68751ee02be6b6688690b416a5d0d1d7f512063c21d025cf47"

      define_method(:install) do
        bin.install "cogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-steer/cogo/releases/download/v0.1.1/cogo_0.1.1_linux_amd64.tar.gz"
      sha256 "6cbed06159dfbd22acf05b3adc0df4fe7172e72bd56fecfe724aae3775480450"
      define_method(:install) do
        bin.install "cogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-steer/cogo/releases/download/v0.1.1/cogo_0.1.1_linux_arm64.tar.gz"
      sha256 "bc570c5b5fb86ae1d0acfe9dfb22653200b940707232d9958c334ca8b37e7d82"
      define_method(:install) do
        bin.install "cogo"
      end
    end
  end

  test do
    assert_match "cogo", shell_output("#{bin}/cogo --version")
  end
end
