# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cogo < Formula
  desc "A terminal-native agentic CLI for Go developers."
  homepage "https://github.com/go-steer/cogo"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-steer/cogo/releases/download/v0.4.0/cogo_0.4.0_darwin_amd64.tar.gz"
      sha256 "25db5dc92875bd4f372aebf6679417ced7839121bcafb4595e883cc7455ced43"

      define_method(:install) do
        bin.install "cogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-steer/cogo/releases/download/v0.4.0/cogo_0.4.0_darwin_arm64.tar.gz"
      sha256 "0eb945498b0852a507c1754f22eb2a0b11aa8c1fd3753c9382332ef87686c422"

      define_method(:install) do
        bin.install "cogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-steer/cogo/releases/download/v0.4.0/cogo_0.4.0_linux_amd64.tar.gz"
      sha256 "b29338de750aff4cae3672c433126e3fe2e3730ad32cc4f19a95f6a9e8dcacd3"
      define_method(:install) do
        bin.install "cogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-steer/cogo/releases/download/v0.4.0/cogo_0.4.0_linux_arm64.tar.gz"
      sha256 "c0d9c4f1468d175e2145f5ec579b1436ef81963486f8a8ed1e82b2dd572b3ad6"
      define_method(:install) do
        bin.install "cogo"
      end
    end
  end

  test do
    assert_match "cogo", shell_output("#{bin}/cogo --version")
  end
end
